name: automl
# conda env create -f environment.yml
# to remove, simply do conda env remove -n mlpipeline
channels:
    - conda-forge
    - defaults
    - anaconda
    - h2oai
dependencies:
    - python=3.7
    - pip
    - numpy
    - pandas
    - matplotlib
    - seaborn
    - statsmodels
    - lmfit
    - xgboost
    - scikit-learn
    - jupyter
    - pandas-profiling
    - h2o
    - tpot
    - pip:
      - auto-sklearn
      - lightgbm
